import { Router, type IRouter } from "express";

const router: IRouter = Router();
const DEFAULT_OLLAMA_URL = "http://localhost:11434";
const allowedTypes = new Set(["task", "bug", "feature", "story"]);
const allowedPriorities = new Set(["low", "medium", "high", "critical"]);
const allowedStatuses = new Set(["todo", "in_progress", "in_review", "done"]);
const priorityRank: Record<string, number> = { critical: 4, high: 3, medium: 2, low: 1 };

function baseUrl(raw?: string) {
  return (raw || DEFAULT_OLLAMA_URL).replace(/\/+$/, "");
}

function asString(value: unknown, fallback = "") {
  return typeof value === "string" && value.trim() ? value.trim() : fallback;
}

function asStringArray(value: unknown) {
  if (Array.isArray(value)) {
    return value.map((item) => String(item).trim()).filter(Boolean).slice(0, 6);
  }
  if (typeof value === "string" && value.trim()) {
    return value
      .split(/\n|;|\.\s+/)
      .map((item) => item.replace(/^[-*]\s*/, "").trim())
      .filter(Boolean)
      .slice(0, 6);
  }
  return [];
}

function parseLooseJson(content: string) {
  try {
    return JSON.parse(content);
  } catch {
    const match = content.match(/\{[\s\S]*\}/);
    if (!match) return {};
    try {
      return JSON.parse(match[0]);
    } catch {
      return {};
    }
  }
}

function inferPriority(text: string) {
  const value = text.toLowerCase();
  if (/\b(security|data loss|crash|broken|blocker|urgent|critical|release)\b/.test(value)) return "critical";
  if (/\b(high|important|risk|deadline|must|core|payment|auth)\b/.test(value)) return "high";
  if (/\b(cleanup|polish|nice|minor|later|optional)\b/.test(value)) return "low";
  return "medium";
}

function inferType(text: string) {
  const value = text.toLowerCase();
  if (/\b(bug|fix|error|crash|broken|fail|issue)\b/.test(value)) return "bug";
  if (/\b(user|workflow|journey|story)\b/.test(value)) return "story";
  if (/\b(feature|add|build|create|implement|support)\b/.test(value)) return "feature";
  return "task";
}

function fallbackStepsFromPrompt(prompt: string, requestedCount: number) {
  const fragments = prompt
    .split(/\n|;|,\s+(?=(?:add|build|create|fix|implement|make|support|design|test)\b)/i)
    .map((item) => item.replace(/^[-*]\s*/, "").trim())
    .filter((item) => item.length > 8)
    .slice(0, requestedCount);

  const source = fragments.length ? fragments : [
    "Clarify the goal and success criteria",
    "Break the work into implementation tasks",
    "Build the highest priority workflow first",
    "Verify behavior with a focused test pass",
  ];

  return source.slice(0, requestedCount).map((title) => ({
    title: title.length > 90 ? `${title.slice(0, 87)}...` : title,
    description: `Task generated from prompt: ${prompt}`,
    type: inferType(title),
    priority: inferPriority(title),
    status: "todo",
    rationale: "Generated by FlowBoard task intelligence from the user prompt.",
    acceptanceCriteria: ["The task is implemented", "The behavior is verified"],
    labels: ["ai-generated"],
    effort: "medium",
  }));
}

function supplementalSteps(prompt: string) {
  const type = inferType(prompt);
  return [
    {
      title: "Clarify scope and success criteria",
      description: `Define the exact outcome for: ${prompt}`,
      type: "task",
      priority: "high",
      status: "todo",
      rationale: "Clear scope prevents vague AI-generated work from becoming hard to execute.",
      acceptanceCriteria: ["Success criteria are written", "Out-of-scope items are listed"],
      labels: ["ai-generated", "planning"],
      effort: "low",
    },
    {
      title: "Design the user workflow",
      description: "Map the screens, controls, and review steps the user needs before tickets are created.",
      type: "story",
      priority: "high",
      status: "todo",
      rationale: "The workflow should be useful before any implementation details are added.",
      acceptanceCriteria: ["Primary workflow is implemented", "Empty, loading, and error states are covered"],
      labels: ["ai-generated", "ux"],
      effort: "medium",
    },
    {
      title: "Implement the core task generation logic",
      description: "Convert prompts into structured tickets with type, status, priority, rationale, labels, and acceptance criteria.",
      type,
      priority: "high",
      status: "todo",
      rationale: "This is the core intelligence layer requested by the user.",
      acceptanceCriteria: ["Multiple tickets are generated", "Each ticket has a priority", "Malformed AI output is normalized"],
      labels: ["ai-generated", "core"],
      effort: "high",
    },
    {
      title: "Add review and create-selected controls",
      description: "Let the user inspect generated tickets, select the ones they want, and create them safely.",
      type: "feature",
      priority: "medium",
      status: "todo",
      rationale: "AI should assist but not write data without user review.",
      acceptanceCriteria: ["Tickets can be selected individually", "Selected tickets are created", "Rejected tickets do not change data"],
      labels: ["ai-generated", "review"],
      effort: "medium",
    },
    {
      title: "Verify generated tickets on the board",
      description: "Test that created tickets appear in the correct project, column, and priority order.",
      type: "task",
      priority: "medium",
      status: "todo",
      rationale: "Generated work must fit the existing Kanban workflow.",
      acceptanceCriteria: ["Created tickets appear on the board", "Priorities and types are preserved", "No duplicate obvious tickets are created"],
      labels: ["ai-generated", "testing"],
      effort: "medium",
    },
    {
      title: "Polish AI failure and no-model states",
      description: "Make Ollama missing, no model selected, timeout, and invalid JSON states clear and recoverable.",
      type: "task",
      priority: "medium",
      status: "todo",
      rationale: "Local AI should feel dependable even when the local model is unavailable.",
      acceptanceCriteria: ["No-model state is actionable", "Timeouts show a useful message", "Invalid responses do not crash the UI"],
      labels: ["ai-generated", "resilience"],
      effort: "low",
    },
  ];
}

function normalizePlan(raw: unknown, prompt: string, requestedCount: number) {
  const data = raw && typeof raw === "object" ? raw as Record<string, unknown> : {};
  const sourceSteps = Array.isArray(data.nextSteps)
    ? data.nextSteps
    : Array.isArray(data.steps)
      ? data.steps
      : Array.isArray(data.tasks)
        ? data.tasks
        : [];

  let nextSteps = sourceSteps
    .filter((item): item is Record<string, unknown> => !!item && typeof item === "object")
    .map((item) => {
      const title = asString(item.title, asString(item.task, asString(item.name, "Review next project step")));
      const type = asString(item.type, inferType(`${title} ${asString(item.description)}`));
      const priority = asString(item.priority, inferPriority(`${title} ${asString(item.description)} ${asString(item.rationale)}`));
      const status = asString(item.status, "todo");

      return {
        title,
        description: asString(item.description, asString(item.details, asString(item.rationale, ""))),
        type: allowedTypes.has(type) ? type : "task",
        priority: allowedPriorities.has(priority) ? priority : "medium",
        status: allowedStatuses.has(status) ? status : "todo",
        rationale: asString(item.rationale, "Suggested by local AI"),
        acceptanceCriteria: asStringArray(item.acceptanceCriteria || item.acceptance_criteria || item.checklist),
        labels: asStringArray(item.labels).length ? asStringArray(item.labels) : ["ai-generated"],
        effort: asString(item.effort, "medium"),
      };
    });

  if (nextSteps.length === 0) {
    nextSteps = fallbackStepsFromPrompt(prompt, requestedCount);
  }

  if (nextSteps.length < requestedCount) {
    const existingTitles = new Set(nextSteps.map((step) => step.title.toLowerCase()));
    for (const step of supplementalSteps(prompt)) {
      if (nextSteps.length >= requestedCount) break;
      if (existingTitles.has(step.title.toLowerCase())) continue;
      nextSteps.push(step);
      existingTitles.add(step.title.toLowerCase());
    }
  }

  nextSteps = nextSteps
    .filter((step) => step.title.length > 0)
    .sort((a, b) => (priorityRank[b.priority] ?? 0) - (priorityRank[a.priority] ?? 0))
    .slice(0, Math.max(1, Math.min(requestedCount, 12)));

  return {
    summary: asString(data.summary, `Generated ${nextSteps.length} prioritized task ticket${nextSteps.length === 1 ? "" : "s"} from the prompt.`),
    blockers: Array.isArray(data.blockers) ? data.blockers.map((item) => String(item)) : [],
    strategy: asString(data.strategy, "Create the highest-priority tickets first, then refine from the board."),
    nextSteps,
  };
}

router.get("/ai/status", async (req, res) => {
  const endpoint = baseUrl(String(req.query.endpoint || ""));
  try {
    const response = await fetch(`${endpoint}/api/tags`, { signal: AbortSignal.timeout(5000) });
    if (!response.ok) {
      res.status(502).json({ ok: false, status: "unavailable", models: [] });
      return;
    }
    const data = await response.json() as { models?: Array<{ name: string; model?: string }> };
    res.json({ ok: true, status: data.models?.length ? "ready" : "no_models", models: data.models ?? [] });
  } catch {
    res.json({ ok: false, status: "unavailable", models: [] });
  }
});

router.post("/ai/project-plan", async (req, res) => {
  const { endpoint, model, project, issues, prompt, taskCount } = req.body ?? {};
  if (!model) {
    res.status(400).json({ error: "Model is required" });
    return;
  }
  const requestedCount = Number.isFinite(Number(taskCount)) ? Math.max(3, Math.min(Number(taskCount), 12)) : 6;

  const system = [
    "You are FlowBoard Task Intelligence, a local AI planner for solo builders.",
    "Return concise JSON only.",
    "Convert the user's prompt into multiple concrete task tickets.",
    `Create ${requestedCount} tickets unless the prompt clearly needs fewer.`,
    "Avoid duplicate tickets that already exist in the provided issue list.",
    "Every ticket must have title, description, type, priority, status, rationale, acceptanceCriteria, labels, and effort.",
    "Use priority critical only for blockers, data loss, security, crashes, or release-stopping work.",
    "Use high for important user-facing or prerequisite work, medium for normal execution, low for polish or optional work.",
    "Keep titles action-oriented and under 90 characters.",
    "Do not claim to change data; the user must review suggestions.",
  ].join(" ");

  const user = JSON.stringify({
    task: prompt || "Review this project and create a prioritized implementation plan.",
    ticketCount: requestedCount,
    project,
    issues,
    existingIssueTitles: Array.isArray(issues) ? issues.map((issue: { title?: string }) => issue.title).filter(Boolean).slice(0, 80) : [],
    responseShape: {
      summary: "short project assessment",
      strategy: "one sentence execution strategy",
      blockers: ["possible blocker"],
      nextSteps: [
        {
          title: "issue title",
          description: "why this matters and what to do",
          type: "task | bug | feature | story",
          priority: "low | medium | high | critical",
          status: "todo | in_progress | in_review | done",
          rationale: "short reason",
          acceptanceCriteria: ["testable done condition"],
          labels: ["short label"],
          effort: "low | medium | high",
        },
      ],
    },
  });

  try {
    const response = await fetch(`${baseUrl(endpoint)}/api/chat`, {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      signal: AbortSignal.timeout(60000),
      body: JSON.stringify({
        model,
        stream: false,
        format: "json",
        options: {
          temperature: 0.2,
          top_p: 0.9,
        },
        messages: [
          { role: "system", content: system },
          { role: "user", content: user },
        ],
      }),
    });

    if (!response.ok) {
      res.status(502).json({ error: "Ollama request failed" });
      return;
    }
    const data = await response.json() as { message?: { content?: string } };
    const content = data.message?.content || "{}";
    res.json(normalizePlan(parseLooseJson(content), prompt || "Review this project and suggest next steps.", requestedCount));
  } catch (error) {
    res.status(500).json({ error: "AI planning failed" });
  }
});

export default router;
